version: "3.9"
    
services:
  db:
    image: redislabs/redismod
    volumes:
      - db_data:/data
    ports:
      - "6379:6379"
    restart: always

  app:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"
    restart: always
    environment: 
      SAYARI_DATABASE_HOST: 'db'

volumes:
  db_data: